### PR TITLE
trust IP of docker network gateway

### LINKED ISSUE #4528: Docker network gateway needs to be a trusted proxy in the config.php
### Steps to reproduce
1. Use AIO in reverse proxy mode (with NPMplus)
2. trigger failed login
3. see docker network gateway as IP

How to fix:
- add IP of docker network gateway to trusted_proxies in the config.php (should maybe be added to the entrypoint.sh/start.sh of the nextcloud container)

### Expected behavior 
log real ip

### Actual behavior 
logs IP of docker network gateway

### Host OS 
Debian 12.5

#### Nextcloud AIO version 
v8.1.0

#### Current channel 
beta

#### Other valuable info 
without IP of the docker gateway and then with it added to the trusted_proxies array in the config.php file
grafik

### PR DESCRIPTION
**Pull request by Zoey2936**
close #4528

### CODE REVIEW

File: Containers/nextcloud/entrypoint.sh [hunk 1]
```diff
@@ -537,8 +537,10 @@ fi
 chmod 775 -R /var/www/html/custom_apps/notify_push/bin/
 php /var/www/html/occ config:system:set trusted_proxies 0 --value="127.0.0.1"
 php /var/www/html/occ config:system:set trusted_proxies 1 --value="::1"
+# IP of docker network gateway
+php /var/www/html/occ config:system:set trusted_proxies 2 --value="$(ip r | grep default | grep -o "[0-9]\+\.[0-9]\+\.[0-9]\+\.1")"
```
Comment (szaimen) [inline Containers/nextcloud/entrypoint.sh:541]: I fear this will overwrite the changes some people might have done already: https://github.com/nextcloud/all-in-one/discussions/2045
So we should probably choose another array key?

File: Containers/nextcloud/entrypoint.sh [hunk 2]
```diff
@@ -537,8 +537,10 @@ fi
...
 if [ -n "$ADDITIONAL_TRUSTED_PROXY" ]; then
-    php /var/www/html/occ config:system:set trusted_proxies 2 --value="$ADDITIONAL_TRUSTED_PROXY"
+    php /var/www/html/occ config:system:set trusted_proxies 3 --value="$ADDITIONAL_TRUSTED_PROXY"
```
Comment (szaimen) [inline Containers/nextcloud/entrypoint.sh:543]: same here?

File: Containers/nextcloud/entrypoint.sh (hunk 1 above)
Comment (szaimen) [reply Containers/nextcloud/entrypoint.sh:541]: Also should we maybe use the same logic like here? https://github.com/nextcloud/all-in-one/blob/17b35a45db08951e7f86e09a971563b407842cc9/Containers/apache/start.sh#L20-L24

File: Containers/nextcloud/entrypoint.sh (hunk 2 above)
Comment (Zoey2936) [reply Containers/nextcloud/entrypoint.sh:543]: What do you mean?

File: Containers/nextcloud/entrypoint.sh (hunk 1 above)
Comment (Zoey2936) [reply Containers/nextcloud/entrypoint.sh:541]: > Also should we maybe use the same logic like here?
> 
> https://github.com/nextcloud/all-in-one/blob/17b35a45db08951e7f86e09a971563b407842cc9/Containers/apache/start.sh#L20-L24

Seems to also work without

File: Containers/nextcloud/entrypoint.sh (hunk 2 above)
Comment (szaimen) [reply Containers/nextcloud/entrypoint.sh:543]: some people might have set the 3 key already...

**Comment by szaimen** [comment]
This is now released with v8.2.1 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel
