### PR TITLE
aio-interface: avoid `Resend` popups on Firefox on start/stop containers

### LINKED ISSUE #7850: "Resend" popup after Stop/Start Containers
### Steps to reproduce
1. On the AIO page click "Stop Containers" or "Start Containers"
2. Wait for streaming of container Stop/Start to finish

### Expected behavior 
When the streaming is done. The page reloads or I'm showing a button or prompt to reload the page.

### Actual behavior 
I'm shown the following popup.

Image

Pressing "Resend" sends another `start` or `stop` POST and then the page reloads. 

I think we don't want to redo the start or stop on success, even though it is idempotent. We want to `GET /containers`

#### Other valuable info 

Image

### PR DESCRIPTION
**Pull request by asavageiv**
Use `location.reload(true)` instead of `reload` or `reload(1)` to ensure we use a GET request when reloading the page after streaming the `start` or `stop` request completes.

See also:
https://stackoverflow.com/a/41122753
https://developer.mozilla.org/en-US/docs/Web/API/Location/reload#forceget

- Fixes #7850
- Close https://github.com/nextcloud/all-in-one/issues/7833

### CODE REVIEW

**Comment by szaimen** [comment]
Thanks you for the fast fix @asavageiv 😊

Please increase the version here and then this should be ready to go from my pov :)
https://github.com/nextcloud/all-in-one/blob/1a7feba6bd60c7c5dc474c9ee3db54d2f2963225/php/templates/layout.twig#L6

File: php/public/forms.js [hunk 1]
```diff
@@ -84,7 +84,7 @@ function showPassword(id) {
             document.getElementById('overlay-log')?.classList.add('visible');
             // Reload the page after the response was fully loaded into the iframe.
             document.querySelector('iframe[name="overlay-log"]').addEventListener('load', () => {
-                location.reload();
+                location.reload(true);
```
Comment (szaimen) [inline php/public/forms.js:87]: So this is the actual fix, right?

**Comment by asavageiv** [comment]
Updated the JS versions and signed the commits. Should be ready now. :)

**Comment by szaimen** [comment]
This is now released with v12.9.2 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel
